### PR TITLE
Fix an issue with opening a deleted container, added test

### LINKED ISSUE #65: Getting a non-existent container returns a non-null value
code to reproduce:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pdc.h"

int
main(int argc, char **argv)
{
    pdcid_t pdc_id, cont_id, cont_prop, cont_id2;
    int     rank = 0, size = 1;
    int     ret_value = 0;

    // create a pdc
#ifdef ENABLE_MPI
    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);
#endif

    pdc_id = PDCinit("pdc");
    cont_prop = PDCprop_create(PDC_CONT_CREATE, pdc_id);
    if (cont_prop <= 0)
        printf("Fail to create container property @ line  %d!\n", __LINE__);

    /*
    // create a container
    cont_id = PDCcont_create("VPIC_cont", cont_prop);
    if (cont_id <= 0)
        printf("Fail to create container @ line  %d!\n", __LINE__);

    if (PDCcont_del(cont_id) != 0)
        printf("Fail to delete container @ line  %d!\n", __LINE__);
    
    if (PDCcont_close(cont_id) != 0)
        printf("Fail to close container @ line  %d!\n", __LINE__);
    */
    
    cont_id = PDCcont_open("VPIC_cont", pdc_id);
    if (cont_id <= 0)
        printf("Fail to open container @ line  %d!\n", __LINE__);
    
#ifdef ENABLE_MPI
    MPI_Finalize();
#endif
    return ret_value;
}
```
uncomment the multi-line comment to test the get-after-delete scenario

### PR DESCRIPTION
**Pull request by houjun**
Fix #65

### CODE REVIEW

File: src/api/pdc_client_connect.c [hunk 1]
```diff
@@ -2376,6 +2376,10 @@ PDC_Client_query_metadata_name_timestep_agg(const char *obj_name, int time_step,
     MPI_Bcast(metadata_server_id, 1, MPI_UINT32_T, 0, PDC_CLIENT_COMM_WORLD_g);
 #else
     ret_value = PDC_Client_query_metadata_name_timestep(obj_name, time_step, out, metadata_server_id);
+    if (ret_value != SUCCEED || NULL == *out) {
+        *out = (pdc_metadata_t *)calloc(1, sizeof(pdc_metadata_t));
```
Comment (jeanbez) [inline src/api/pdc_client_connect.c]: Is this freed somewhere?

File: src/server/pdc_client_server_common.c [hunk 2]
```diff
@@ -1685,7 +1685,10 @@ HG_TEST_RPC_CB(container_query, handle)
     HG_Get_input(handle, &in);
 
     PDC_Server_find_container_by_name(in.cont_name, &cont_entry);
```
Comment (zhangwei217245) [inline src/server/pdc_client_server_common.c:1687]: this line reminds me the 'object listing API for a specified container' we discussed last time. 

Maybe we should consider having such an API so that the container can be used more easily for retrieving a particular set of objects within a specified container?

**Review by zhangwei217245 — COMMENTED** [review]
Please add an issue for a new feature 'list all objects or all object IDs under the specified container'

File: src/api/pdc_client_connect.c (hunk 1 above)
Comment (houjun) [reply src/api/pdc_client_connect.c]: Yes, it should be freed by PDC_obj_close

File: src/server/pdc_client_server_common.c (hunk 2 above)
Comment (houjun) [reply src/server/pdc_client_server_common.c:1687]: There is an API PDCcont_get_objids() that has not been properly implemented.
