### PR TITLE
Fix container tag delete error

### LINKED ISSUE #66: Deleting a container tag segfaults
Code to reproduce:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pdc.h"

int
main(int argc, char **argv)
{
    pdcid_t pdc_id, cont_id, cont_prop, cont_id2;
    int     rank = 0, size = 1;
    int     ret_value = 0;

    // create a pdc
#ifdef ENABLE_MPI
    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);
#endif

    pdc_id = PDCinit("pdc");
    // create a container
    cont_id = PDCcont_create("cont", cont_prop);
    if (cont_id <= 0)
        printf("Fail to create container @ line  %d!\n", __LINE__);

    //put tag
    if (PDCcont_put_tag(cont_id, "a", "b", 1) != 0)
        printf("Fail to put tag @ line  %d!\n", __LINE__);

    //delete tag
    PDCcont_del_tag(cont_id, "a"); //SEGFAULT HERE

    PDCcont_close(cont_id);
    
    PDCclose(pdc_id);
    
#ifdef ENABLE_MPI
    MPI_Finalize();
#endif
    return ret_value;
}
```

I think this is because PDCcont_del_tag delegates to PDCobj_del_tag

### PR DESCRIPTION
**Pull request by houjun**
Fix #66

### CODE REVIEW

File: src/api/pdc_client_connect.c [hunk 1]
```diff
@@ -7454,6 +7409,67 @@ PDC_Client_query_kvtag_col(const pdc_kvtag_t *kvtag, int *n_res, uint64_t **pdc_
     FUNC_LEAVE(ret_value);
 }
 
+perr_t
+PDCtag_delete(pdcid_t obj_id, char *tag_name, int is_cont)
```
Comment (jeanbez) [inline src/api/pdc_client_connect.c:7414]: Can you make sure this function has documentation on top of it?

File: src/server/pdc_server_metadata.c [hunk 2]
```diff
@@ -2798,23 +2799,31 @@ PDC_Server_del_kvtag(metadata_get_kvtag_in_t *in, metadata_add_tag_out_t *out)
...
 #endif
 
-    lookup_value = hash_table_lookup(metadata_hash_table_g, &hash_key);
-    if (lookup_value != NULL) {
-        pdc_metadata_t *target;
-        target = find_metadata_by_id_from_list(lookup_value->metadata, obj_id);
-        if (target != NULL) {
-            PDC_del_kvtag_value_from_list(&target->kvtag_list_head, in->key);
-            out->ret = 1;
+    // Look cont tags first
```
Comment (zhangwei217245) [inline src/server/pdc_server_metadata.c]: why do we look up container tags first? I think the lookups against object tags could be more frequent. 

also, shall we consider having a better separation between the lookups on object tags and container tags? Maybe a separate function call or a separate flag to differentiate between obj/cont, etc.

File: src/tests/cont_tags.c [hunk 3]
```diff
@@ -76,99 +75,131 @@ main(int argc, char **argv)
...
     if (ret != SUCCEED) {
         printf("Put tag failed at container 1\n");
-        ret_value = 1;
+        return -1;
     }
     ret = PDCcont_put_tag(cont, "some tag 2", tag_value2, PDC_STRING, strlen(tag_value2) + 1);
     if (ret != SUCCEED) {
         printf("Put tag failed at container 1\n");
-        ret_value = 1;
+        return -1;
```
Comment (zhangwei217245) [inline src/tests/cont_tags.c:90]: Let's put this convention into developer's document: all functions return negative for failure and return non-negative for success. 

Also, we probably should consider a series of return code to represent for different status of the function call, just similar to what the HTTP status code is used in RESTful API call (doesn't have to be exactly the same set of status code in HTTP).

File: src/api/pdc_client_connect.c (hunk 1 above)
Comment (houjun) [reply src/api/pdc_client_connect.c:7414]: Changed it to a static function, public functions have been properly documented in the header files.

File: src/api/pdc_client_connect.c [hunk 4]
```diff
@@ -7454,6 +7409,68 @@ PDC_Client_query_kvtag_col(const pdc_kvtag_t *kvtag, int *n_res, uint64_t **pdc_
...
+    else {
+        obj_prop = PDC_obj_get_info(obj_id);
+        meta_id  = obj_prop->obj_info_pub->meta_id;
+    }
+
+    server_id = PDC_get_server_by_obj_id(meta_id, pdc_server_num_g);
+
+    debug_server_id_count[server_id]++;
+
+    if (PDC_Client_try_lookup_server(server_id, 0) != SUCCEED)
```
Comment (zhangwei217245) [inline src/api/pdc_client_connect.c:7441]: back in 2018, I remembered that such a lookup was necessary before creating an RPC call... What was the reason? If there was an issue with MercuryRPC, is it fixed in the new version now?

I'm asking this because I also noticed this in my DART integration where I need to lookup servers first before issuing DART query...

File: src/api/pdc_client_connect.c [hunk 5]
```diff
@@ -7454,6 +7409,68 @@ PDC_Client_query_kvtag_col(const pdc_kvtag_t *kvtag, int *n_res, uint64_t **pdc_
...
+    // Fill input structure
+    in.obj_id = meta_id;
+
+    if (is_cont)
+        in.hash_value = PDC_get_hash_by_name(cont_prop->cont_info_pub->name);
+    else
+        in.hash_value = PDC_get_hash_by_name(obj_prop->obj_info_pub->name);
+    in.key = tag_name;
+
+    hg_ret = HG_Forward(metadata_del_kvtag_handle, metadata_add_tag_rpc_cb /*reuse*/, &lookup_args, &in);
```
Comment (zhangwei217245) [inline src/api/pdc_client_connect.c:7457]: I would suggest we add more comments here to note that there is not much logic in the add_tag_rpc_cb function so that's why it can be reused here for a tag-delete operation...

**Review by zhangwei217245 — CHANGES_REQUESTED** [review]
2 comments that needs to be addressed:

1. why are we adjusting the kvtag querying order to 'cont first' now?
2. the reuse of 'metadata_tag_add_rpc_cb' is not a good practice suppose if future developers would like to add more logic in this cb function. We should add an additional call back function specifically for tag_delete operation.

File: src/server/pdc_server_metadata.c (hunk 2 above)
Comment (houjun) [reply src/server/pdc_server_metadata.c]: Changed to check obj first.
Yes, ideally we should pass whether it is querying on an object or a container, will create a new issue.

File: src/api/pdc_client_connect.c (hunk 4 above)
Comment (houjun) [reply src/api/pdc_client_connect.c:7441]: We have switched to an "on-demand" server lookup process, a client only looks up a server to establish a connection when it needs to send a request to the target server.

**Review by jeanbez — APPROVED** [review]

File: src/api/pdc_client_connect.c (hunk 4 above)
Comment (zhangwei217245) [reply src/api/pdc_client_connect.c:7441]: Why did we switch to such an 'on-demand' server lookup process? Why don't we perform server lookup when initializing the clients? 

With this 'on-demand' server lookup, we would need to add server lookup code every time before issuing an RPC call, which can cause some overhead for each RPC call and also may significantly increase the amount of repetitive code as more RPC calls are defined in our project.

Comment (houjun) [reply src/api/pdc_client_connect.c:7441]: It takes a long time for the client-server lookup if it is done at the beginning, think about having 64 servers and 64*64=4096 clients, each server would receive 4096 connection requests at the same time, a lot of these connections are likely not needed. 
The on-demand server lookup only performs the lookup the **first** time a client needs a connection to the server and it caches the server address, PDC_Client_try_lookup_server() will do nothing for the second, third... connections.

**Review by zhangwei217245 — APPROVED** [review]

File: src/api/pdc_client_connect.c (hunk 4 above)
Comment (zhangwei217245) [reply src/api/pdc_client_connect.c:7441]: Okay! I'm convinced now :-)
